### YamlMime:ManagedReference
items:
- uid: TimeCockpit.Data.Security
  commentId: N:TimeCockpit.Data.Security
  id: TimeCockpit.Data.Security
  children:
  - TimeCockpit.Data.Security.MemberAccessPermission
  - TimeCockpit.Data.Security.MemberAccessPermissions
  - TimeCockpit.Data.Security.Permission
  - TimeCockpit.Data.Security.PermissionEvaluator
  - TimeCockpit.Data.Security.PermissionTarget
  - TimeCockpit.Data.Security.PermissionType
  - TimeCockpit.Data.Security.PermissionTypeInfo
  langs:
  - csharp
  - vb
  name: TimeCockpit.Data.Security
  nameWithType: TimeCockpit.Data.Security
  fullName: TimeCockpit.Data.Security
  type: Namespace
  assemblies:
  - TimeCockpit.Data
references:
- uid: TimeCockpit.Data.Security.PermissionType
  commentId: T:TimeCockpit.Data.Security.PermissionType
  parent: TimeCockpit.Data.Security
  isExternal: false
  name: PermissionType
  nameWithType: PermissionType
  fullName: TimeCockpit.Data.Security.PermissionType
- uid: TimeCockpit.Data.Security.MemberAccessPermission
  commentId: T:TimeCockpit.Data.Security.MemberAccessPermission
  parent: TimeCockpit.Data.Security
  isExternal: false
  name: MemberAccessPermission
  nameWithType: MemberAccessPermission
  fullName: TimeCockpit.Data.Security.MemberAccessPermission
- uid: TimeCockpit.Data.Security.MemberAccessPermissions
  commentId: T:TimeCockpit.Data.Security.MemberAccessPermissions
  parent: TimeCockpit.Data.Security
  isExternal: false
  name: MemberAccessPermissions
  nameWithType: MemberAccessPermissions
  fullName: TimeCockpit.Data.Security.MemberAccessPermissions
- uid: TimeCockpit.Data.Security.Permission
  commentId: T:TimeCockpit.Data.Security.Permission
  parent: TimeCockpit.Data.Security
  isExternal: false
  name: Permission
  nameWithType: Permission
  fullName: TimeCockpit.Data.Security.Permission
- uid: TimeCockpit.Data.Security.PermissionEvaluator
  commentId: T:TimeCockpit.Data.Security.PermissionEvaluator
  isExternal: false
  name: PermissionEvaluator
  nameWithType: PermissionEvaluator
  fullName: TimeCockpit.Data.Security.PermissionEvaluator
- uid: TimeCockpit.Data.Security.PermissionTarget
  commentId: T:TimeCockpit.Data.Security.PermissionTarget
  parent: TimeCockpit.Data.Security
  isExternal: false
  name: PermissionTarget
  nameWithType: PermissionTarget
  fullName: TimeCockpit.Data.Security.PermissionTarget
- uid: TimeCockpit.Data.Security.PermissionTypeInfo
  commentId: T:TimeCockpit.Data.Security.PermissionTypeInfo
  isExternal: false
  name: PermissionTypeInfo
  nameWithType: PermissionTypeInfo
  fullName: TimeCockpit.Data.Security.PermissionTypeInfo
- uid: TimeCockpit.Data.Security
  commentId: N:TimeCockpit.Data.Security
  isExternal: false
  name: TimeCockpit.Data.Security
  nameWithType: TimeCockpit.Data.Security
  fullName: TimeCockpit.Data.Security
