### YamlMime:ManagedReference
items:
- uid: TimeCockpit.Data.DataModel.View.IApplicationPartConfiguration
  commentId: T:TimeCockpit.Data.DataModel.View.IApplicationPartConfiguration
  id: IApplicationPartConfiguration
  parent: TimeCockpit.Data.DataModel.View
  children: []
  langs:
  - csharp
  - vb
  name: IApplicationPartConfiguration
  nameWithType: IApplicationPartConfiguration
  fullName: TimeCockpit.Data.DataModel.View.IApplicationPartConfiguration
  type: Interface
  source:
    id: IApplicationPartConfiguration
    path: E:\Projects\TimeCockpit.Development\Production\V 1.53\Hotfix\Source\TimeCockpit.Data\WPF\TimeCockpit.Data\DataModel\View\IApplicationPartConfiguration.cs
    startLine: 13
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.DataModel.View
  summary: "\nActs as a marker interface for the configuration of an application part.\n"
  example: []
  syntax:
    content: 'public interface IApplicationPartConfiguration : INotifyPropertyChanged'
    content.vb: >-
      Public Interface IApplicationPartConfiguration
          Inherits INotifyPropertyChanged
  inheritedMembers:
  - System.ComponentModel.INotifyPropertyChanged.PropertyChanged
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: TimeCockpit.Data.DataModel.View
  commentId: N:TimeCockpit.Data.DataModel.View
  isExternal: false
  name: TimeCockpit.Data.DataModel.View
  nameWithType: TimeCockpit.Data.DataModel.View
  fullName: TimeCockpit.Data.DataModel.View
- uid: System.ComponentModel.INotifyPropertyChanged.PropertyChanged
  commentId: E:System.ComponentModel.INotifyPropertyChanged.PropertyChanged
  parent: System.ComponentModel.INotifyPropertyChanged
  isExternal: true
  name: PropertyChanged
  nameWithType: INotifyPropertyChanged.PropertyChanged
  fullName: System.ComponentModel.INotifyPropertyChanged.PropertyChanged
- uid: System.ComponentModel.INotifyPropertyChanged
  commentId: T:System.ComponentModel.INotifyPropertyChanged
  parent: System.ComponentModel
  isExternal: true
  name: INotifyPropertyChanged
  nameWithType: INotifyPropertyChanged
  fullName: System.ComponentModel.INotifyPropertyChanged
- uid: System.ComponentModel
  commentId: N:System.ComponentModel
  isExternal: false
  name: System.ComponentModel
  nameWithType: System.ComponentModel
  fullName: System.ComponentModel
